# Generated by Django 3.2 on 2023-05-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_tutor_is_approved'),
        ('recall', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
