# Generated by Django 3.2 on 2023-05-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reason_of_registration',
        ),
        migrations.AlterField(
            model_name='student',
            name='tutors',
            field=models.ManyToManyField(blank=True, null=True, to='users_app.Tutor'),
        ),
    ]
