# Generated by Django 3.2 on 2023-05-18 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20230507_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='voted_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.tutor'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
